- content/languages/javascript/testing.md
- content/refs/javascript-ref.md
- src/templates/MarkdownPage.vue
Handle pages not in `MarkdownPage`
> Improve prev/next navigation

- .github/workflows/lint.yml
- .prettierignore
- package.json
- schemas/term.graphql
This should apply Prettier fixes to changes made on GitHub actions. Usual workflow shouldn't be affected because it already has pre-commit hook set up.
> Prettier with GitHub Actions

- gridsome.config.js
- src/templates/MarkdownPage.vue
> Add "Edit on GitHub" link for Markdown pages

- src/pages/Glossary.vue
> Adjust maximum width of glossary terms

- src/pages/Index.vue
> Make landing icons clickable

- content/getting-started.md
- content/getting-started/community.md
- content/getting-started/finding-kata.md
- content/getting-started/index.md
- content/getting-started/registering.md
- content/getting-started/setting-up.md
- content/getting-started/solutions.md
- content/getting-started/solving-kata.md
- gridsome.config.js
- Create a directory for sub-pages and assets
- Create sidebar
- Add stub pages
For #40
> Prepare Getting Started doc

- .github/workflows/lint.yml
See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
> Fix triggering new workflow after Prettier fix

- content/languages/python/codewars-test/index.md
- data/glossary.yml
> Correct pulrals (katas >kata, .)

- src/templates/MarkdownPage.vue
> Change selection color of code blocks

- package.json
- src/assets/styles.css
- src/components/LayoutHeader.vue
- src/components/OnThisPage.vue
- src/components/Search.vue
- src/components/Sidebar.vue
- src/layouts/Default.vue
- src/pages/Glossary.vue
- src/pages/Index.vue
- src/pages/Languages.vue
- src/templates/KindT.vue
- src/templates/Language.vue
- src/templates/MarkdownPage.vue
- src/templates/Tag.vue
- tailwind.config.js
- yarn.lock
- https://blog.tailwindcss.com/tailwindcss-typography
- https://github.com/tailwindcss/typography
> Use Tailwind CSS Typography plugin

- content/getting-started/community.md
I accidentally un-drafted this PR, is there a way to mark it as draft again?
> Getting started: community

- content/getting-started/solutions.md
Incorrect Prev navigation link in Getting started: Solutions
> Getting started: Fix navigation link

- gridsome.server.js
- src/templates/KindT.vue
> Add slug field to sort case insensitively

- gridsome.server.js
https://github.com/codewars/docs/issues/101#issuecomment-667073333
Closes #101
> Don't split camel cased word for slug

- data/glossary.yml
Adding some new lines to split some definitions into different paragraphs and increase a bit their readability
> split some definitions

- src/pages/Glossary.vue
https://github.com/codewars/docs/pull/123#issuecomment-672226867
> Increase space between terms and term groups

- tailwind.config.js
Fixes https://github.com/codewars/docs/issues/152
> Fix line break within padding of code span

- gridsome.config.js
- package.json
- src/assets/styles.css
- yarn.lock
```markdown
- **foo bar**{id="foo-bar"}
```
> Add remark-attr to support adding ids for linking

- content/languages/python/codewars-test/index.md
- gridsome.config.js
- package.json
- src/templates/MarkdownPage.vue
- yarn.lock
```markdown
:::keyword optional_title
some content
:::
```
See https://gridsome.org/plugins/gridsome-plugin-remark-container
> Add remark-container plugin to support callouts

- content/references/kata-ranking/approval-retire-criteria.md
Motivated by [this question](https://www.codewars.com/topics/523606261ace3f92c3000113#5fa9ee9e8fda16001e18e168).
Deploy preview [here](https://deploy-preview-165--reverent-edison-2864ea.netlify.app/references/kata-ranking/approval-retire-criteria/#eligibility-for-approval).
> Kata approval: Describe how requirements are calculated

- content/references/kata-ranking/approval-retire-criteria.md
> trying to resolve formatting troubles (reference/kata-ranking/auto-retirement)

- content/languages/cpp/igloo/stringizers.md
- content/recipes/authoring/kata-snippets/reference-solution.md
PR addressing issues reported by DSL in his broken review here: https://github.com/codewars/docs/pull/151#commitcomment-44064762
@DonaldKellett if it's OK, just merge the PR.
> Fix wording and grammar

- content/authoring/guidelines/kata.md
- content/authoring/guidelines/translation.md
- gridsome.config.js
I think it would be the last important missing piece to the set of authoring guidelines. I was not sure how to express some ideas, so I just went with what I have. Any hints are welcome.
Discussion: #149 
Deploy preview: [here](https://deploy-preview-182--reverent-edison-2864ea.netlify.app/authoring/guidelines/kata/)
> Authoring guidelines: creating a kata

- content/authoring/kata/adding-images.md
Discussion: #186 
Deploy preview: [here](https://deploy-preview-187--reverent-edison-2864ea.netlify.app/authoring/kata/adding-images/)
> Adding images to descriptions

- src/layouts/Default.vue
> Show the language page on the sidebar

- content/concepts/kata/beta-process.md
- gridsome.config.js
Import from old wiki as a stub. Put in proper place in new docs, set up navigation
Discussion: #200 
Preview: [here](https://deploy-preview-220--reverent-edison-2864ea.netlify.app/concepts/kumite/)
> Organize kumite

- content/authoring/kata/read-solution-file.md
Discussion: #222 
Preview: [here](https://deploy-preview-223--reverent-edison-2864ea.netlify.app/authoring/kata/read-solution-file/)
> Read solution file

- src/main.js
Closes https://github.com/codewars/docs/issues/226
> Fix scroll position affected by sidebars

- content/languages/c/authoring/index.md
Maybe having more explicit note in the C tutorial will make the #230 obsolete, unnecessary, or will allow for reducing it?
> Redone note on memory management

- content/languages/python/authoring/index.md
correct actual/expected inversion in the python example test suite
> correct python test suite examples

- content/languages/javascript/authoring.md
Reported with #261 
Preview: [here](https://deploy-preview-262--reverent-edison-2864ea.netlify.app/languages/javascript/authoring/#example-test-suite)
> Fix actual/expected order in example test suite

- content/languages/javascript/authoring.md
- content/languages/python/codewars-test/index.md
Motivated by #266 
Preview: [for Python](https://deploy-preview-268--reverent-edison-2864ea.netlify.app/languages/python/codewars-test/#organization-of-tests), [for JavaScript](https://deploy-preview-268--reverent-edison-2864ea.netlify.app/languages/javascript/authoring/#dynamically-generated-test-cases).
> Notes on variables captured in test closures

- content/training/troubleshooting.mdx
Attempt to reconstruct prematurely closed #288
> Troubleshooting review

- tailwind.config.js
> Fix broken TOML code

- src/css/custom.css
> Fix unreadable link in code span

- src/css/custom.css
> Fix thin active ToC item

- content/languages/python/index.md
Added Python 3.8 to the list of available language versions.
> Added Python 3.8

- content/training/troubleshooting.mdx
Fixed a link to code formatting reference.
> Update link to code formatting reference

- content/training/troubleshooting.mdx
Migrated a bullet point from https://github.com/codewars/codewars.com/wiki/Troubleshooting-your-solution#post-discourse
> Remark on posting solutions in discourse after solving a kata

- content/concepts/kata/satisfaction-rating.md
> fix(mistake): fixed the mistake

- content/concepts/kata/tests.md
> fixed small typo

- content/languages/index.md
- content/languages/lambdacalc/authoring.md
- content/languages/lambdacalc/index.md
- content/languages/lambdacalc/lc-test.md
- sidebars.js
Add documentation of `lc-test`, and small authoring guide.
> Add Lambda Calculus

- content/concepts/kata/tests.md
Change "worh" to "worth" in 3rd paragraph
> Fix typo in tests.md

- content/languages/powershell/index.md
- content/languages/powershell/pester.md
Continuing to merge test library-specific code into the test library instead of the language page.
> Combine Pester

- content/languages/javascript/mocha.md
[Preview](https://deploy-preview-444--reverent-edison-2864ea.netlify.app/languages/javascript/mocha/)
> Add basic Mocha example

- content/languages/typescript/mocha.md
[Preview](https://deploy-preview-445--reverent-edison-2864ea.netlify.app/languages/typescript/mocha/)
> Add basic TS Mocha example

- content/languages/shell/rspec.md
[Preview](https://deploy-preview-446--reverent-edison-2864ea.netlify.app/languages/shell/rspec/)
> Add basic Shell/RSpec example

- content/languages/fsharp/index.md
- content/languages/fsharp/nunit.md
- sidebars.js
https://deploy-preview-478--reverent-edison-2864ea.netlify.app/
> Add F# 6 and NUnit example

- content/languages/ruby/index.md
- content/languages/ruby/rspec.md
- sidebars.js
https://deploy-preview-480--reverent-edison-2864ea.netlify.app/
> Add RSpec example

- content/community/moderation/index.mdx
- Removes steffan153, who deleted their account long time ago,
- Adds Kacarott
[Preview](https://deploy-preview-505--reverent-edison-2864ea.netlify.app/community/moderation#members)
> Update members of the mod team
