codewars/docs

- src/components/ToggleDarkMode.vue
`?dark=1` can force dark mode. This is useful when embedding a page.
> Override theme with search param

- content/languages/python/codewars-test-famework/index.md
- Remove v2 from title
- Move acknowledgement to last
- Reword headings
- Don't mention assertions _can_ be anywhere
- Clarify `Test` alias
- Remove unnecessary `<br>` and `<hr>`
- Remove information about the current output. This is about the framework and shouldn't include minor details about the output.
> Clean up Python test framework doc

- data/glossary.yml
Starting point, to see how it behaves.
I didn't update the stump that was already there (dan/kyus/...)
note @kazk : what do you expect to write about TDD considering the `TODO` note that is there?
> Add some words to glossary

- src/pages/Glossary.vue
Also move the external link icon to the left to make it more obvious.
Closes #37
> Adjust indentations of term links

- src/templates/KindT.vue
Increased to 20 for now. We'll adjust when we decide how to present these links.
See #64
> Increase perPage to 20

- src/pages/Glossary.vue
- src/pages/Languages.vue
- src/templates/Language.vue
- src/templates/MarkdownPage.vue
- tailwind.config.js
Surrounding code span with backticks can be annoying. Change to use the rounded border like the updated style on Codewars.
> Change code span style

- content/references/markdown/index.md
* I feel like I've been too much verbose again, no? :/
* I didn't put the code blocks in there because of the `extensions` page. What should I do?
- a section with a link to the extension page and put everything there?
- or a section and talk about the simple code blocks (wwithout labels), then a link to the extensions?
Subsequent question: in the extensions page, there is the last section about math typesetting. Maybe it should be put into another page?
> Update markdown reference

- src/assets/styles.css
- src/main.js
Fixes the following (note the first bullet point):
which is caused by a hack for preventing the sticky header covering the linked element. This hack was used instead of `scroll-margin-top` because I couldn't figure out why `scroll-margin-top` didn't work. This bug made me look into it further and found that it's caused by Vue router's `scrollBehavior` not configured to handle it.
> Use scroll-margin-top

- tailwind.config.js
The weird break was caused by `code::before`/`code::after` that's used to remove the default backticks around code spans.
Fixes https://github.com/codewars/docs/issues/168
> Fix code span styling

- content/authoring/guidelines/preloaded.md
- content/authoring/guidelines/reference-solution.md
- content/authoring/guidelines/submission-tests.md
- content/authoring/guidelines/translation.md
A note that content which does not conform to quality guidelines can be retired/rejected/removed has been added to "General" section. I think it's enough to have it in one general place rather than repeat it on every page.
> Authoring guidelines: Removed redundant notes

- content/languages/python/authoring/index.md
- content/languages/python/codewars-test/index.md
Discussion: #197 
Deploy preview: [here](https://deploy-preview-198--reverent-edison-2864ea.netlify.app/languages/python/codewars-test/)
I wanted to remove parts which became redundant after introducing "Authoring Python kata" doc, and to make it look more like an actual reference rather than a HOWTO. I hope I did not remove too much, but if you think something is missing, let me know.
> Improve docs on Python testing framework

- content/languages/cpp/igloo/stringizers.md
Missing blank line causes one code block to render incorrectly.
> Fix markdown formatting of a code block

- content/community/moderation.md
- organize by severity,
- mention content issues board
> Improve "how to get in touch" section

- content/authoring/guidelines/kata.mdx
- docusaurus.config.js
- sidebars.js
- sitePlugin.js
- src/components/Anchored.jsx
- src/css/custom.css
Usage:
```jsx
import A from "@components/Anchored";
**<A id="foo">foo</A>**
```
See #157
---
https://deploy-preview-280--reverent-edison-2864ea.netlify.app/authoring/guidelines/kata#.novelty
> Add Anchored component

- content/meta/docs.mdx
- docusaurus.config.js
- package.json
- sidebars.js
- sitePlugin.js
- src/components/Anchored.jsx
- src/css/custom.css
- tailwind.config.js
- yarn.lock
Tried to make it similar to the previous version. I haven't found an easy way to change the icons, and `warning` has a fire icon.
Also starting a meta doc (documentation about the Codewars docs). This page can be used to summarize the features, and test the styles. https://deploy-preview-286--reverent-edison-2864ea.netlify.app/meta/docs
Closes #281
> Fix admonition style

- .github/workflows/docsearch.yml
- docsearch.json
- docusaurus.config.js
- src/css/custom.css
- yarn.lock
Unfortunately, we didn't qualify for the free hosted version, but we can [run the crawler](https://docsearch.algolia.com/docs/run-your-own) every day in GitHub Actions. Hopefully, the free plan is enough for us.
Closes #4
> Add search with DocSearch

- docusaurus.config.js
This is necessary because the search page doesn't have the sidebar, and we have the link brand link to codewars.com.
> Add Docs to navbar

- content/languages/cpp/authoring/index.md
Requested by a user:
Stress clearly that issues with `using` are caused by Codewars setup and not that it's a general language guideline.
Deploy preview: [here](https://deploy-preview-358--reverent-edison-2864ea.netlify.app/languages/cpp/authoring#using-directives)
> Reword paragraph on `using`

- content/languages/factor/authoring.md
- content/languages/factor/testest.md
- content/languages/python/codewars-test.mdx
- sidebars.js
I roughly used the existing JavaScript guide as a template, and also added some Factor specific content.
I thought perhaps nomennescio could look over it for errors or changes, but it might be easier to "pull now, fix later" so that he can read directly in the docs.
Preview: [here](https://deploy-preview-367--reverent-edison-2864ea.netlify.app/languages/factor/authoring)
> Added documentation for Factor

- content/languages/haskell/index.md
QuickCheck has been always available, but it's a transitive dependency
and not listed in `package.yaml`. It will be installed explicitly in the
next version.
> haskell: Include QuickCheck

- sidebars.js
We need to either:
- generate a page from `glossary.yml` like before, or
- switch to Markdown and manually maintain order and headers
- can write a script to migrate
> Hide glossary from sidebar for now

- content/curation/guidelines/kata.md
Make it easier to point users to an information which can help them to assign an accurate rank when approving kata.
> Add information on rank assessments API endpoint

- content/languages/php/phpunit.md
See comments in #399: https://github.com/codewars/docs/pull/399#pullrequestreview-1011406669. This PR clarifies the surprising behavior of `assertEquals` and provides a few alternatives.
> Avoid assertEquals and clarify PHP

- content/authoring/tutorials/create-first-kata.mdx
- content/community/following.mdx
- content/concepts/kata/translations.mdx
- content/gamification/honor.mdx
- content/gamification/index.mdx
- content/gamification/ranks.mdx
- content/getting-started/finding-kata.mdx
- content/getting-started/kata-solved.mdx
- content/getting-started/setting-up.mdx
- content/getting-started/solving-kata.mdx
- content/languages/python/codewars-test.mdx
- content/references/kata-trainer.mdx
- content/references/markdown/extensions.mdx
- content/training/troubleshooting.mdx
- src/css/custom.css
This will work when viewing Markdown on GitHub as well.
https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/
> Replace `ThemedImage` with GitHub's approach

- content/languages/index.md
- content/languages/riscv/cgreen.md
- content/languages/riscv/index.md
- sidebars.js
Closes #438 
Closes #439
It might be better to address #440 after modifying `bin/run` in [codewars/riscv](https://github.com/codewars/riscv) to allow text output when solving locally.
> Add RISC-V to the list of Beta languages

- content/curation/references/approval-retirement-criteria.md
Preview: [here](https://deploy-preview-450--reverent-edison-2864ea.netlify.app/curation/references/approval-retirement-criteria#auto-retire).
> Add a note on auto-retirement of "hopeless" kata

- content/languages/python/authoring.md
- Remove obsolete note on performance problems of RNG.
- Remove restriction for reference solution being in a top level scope.
Preview: [here](https://deploy-preview-451--reverent-edison-2864ea.netlify.app/languages/python/authoring#reference-solution).
> Update Python authoring guide

- content/languages/cpp/igloo/stringizers.md
Resolves #449 .
Preview: [here](https://deploy-preview-456--reverent-edison-2864ea.netlify.app/languages/cpp/igloo/stringizers#precision-loss-in-formatted-double-values)
> Add info on stringizers for doubles

- content/languages/riscv/index.md
Simple edit to reflect the extra extensions supported in codewars/riscv#7. Also adds links to specifications since some extensions are not included in the RISC-V Spec.
Still not completely happy with line 13, I feel like it's not visually appealing but the ISA string the closest there is to a version number. Maybe listing the QEMU version? Not sure.
As I will comment in codewars/riscv#7 as well, Zbkx is not necessary as it's in both Zk and Zks shorthands.
> Update RISC-V ISA documentation

- content/languages/julia/index.md
https://github.com/JuliaAttic/FactCheck.jl hasn't been updated in years and doesn't work with current Julia versions
> docs/julia/index.md: update link to FactCheck.jl

- content/getting-started/setting-up.mdx
Fix the issue reported by an user in https://github.com/codewars/codewars.com/issues/3286
> Fixing the missing links in the documentation

- content/languages/haskell/index.md
* update to GHC 9.2.5, updating stackage link to LTS 20.10
* add link to container repository
* add version table to packages
> Update Haskell to GHC 9.2.5

- content/curation/howtos/fixing.md
- content/curation/translation.md
- sidebars.js
[Preview](https://deploy-preview-511--reverent-edison-2864ea.netlify.app/curation/howtos/fixing).
> Howto fix kata

- content/languages/rust/index.md
This also includes the current versions of the dependencies, as listed in `Cargo.toml`.
> Update the rust documentation to reference the current version
